CREATE EXTENSION IF NOT EXISTS vector;

ALTER TABLE member_consents
    DROP CONSTRAINT chk_member_consents_type;

ALTER TABLE member_consents
    ADD CONSTRAINT chk_member_consents_type
        CHECK (consent_type IN (
            'TERMS',
            'PRIVACY',
            'LOCATION',
            'MARKETING',
            'AI_PROCESSING',
            'OVERSEAS_TRANSFER'
        ));

CREATE TABLE member_preference_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    preference_text TEXT NOT NULL,
    embedding VECTOR(1536),
    embedding_model VARCHAR(100),
    embedding_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_member_preference_embeddings PRIMARY KEY (id),
    CONSTRAINT fk_member_preference_embeddings_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT uq_member_preference_embeddings_member UNIQUE (member_id),
    CONSTRAINT chk_member_preference_embeddings_text
        CHECK (char_length(btrim(preference_text)) > 0),
    CONSTRAINT chk_member_preference_embeddings_status
        CHECK (embedding_status IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT chk_member_preference_embeddings_completed
        CHECK (
            embedding_status <> 'COMPLETED'
            OR (embedding IS NOT NULL AND embedding_model IS NOT NULL)
        )
);

CREATE INDEX idx_member_preference_embeddings_status
    ON member_preference_embeddings (embedding_status);
