CREATE TABLE festival_meeting_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    festival_id BIGINT NOT NULL,
    kakao_place_id VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    map_x NUMERIC(13,10) NOT NULL,
    map_y NUMERIC(13,10) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'INACTIVE',
    assignment_order INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_festival_meeting_points PRIMARY KEY (id),
    CONSTRAINT fk_festival_meeting_points_festival
        FOREIGN KEY (festival_id) REFERENCES festivals (id) ON DELETE RESTRICT,
    CONSTRAINT uq_festival_meeting_points_festival_kakao
        UNIQUE (festival_id, kakao_place_id),
    CONSTRAINT chk_festival_meeting_points_kakao_place_id
        CHECK (btrim(kakao_place_id) <> ''),
    CONSTRAINT chk_festival_meeting_points_name CHECK (btrim(name) <> ''),
    CONSTRAINT chk_festival_meeting_points_address CHECK (btrim(address) <> ''),
    CONSTRAINT chk_festival_meeting_points_map_x CHECK (map_x BETWEEN -180 AND 180),
    CONSTRAINT chk_festival_meeting_points_map_y CHECK (map_y BETWEEN -90 AND 90),
    CONSTRAINT chk_festival_meeting_points_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT chk_festival_meeting_points_assignment_order CHECK (assignment_order >= 0)
);

CREATE INDEX idx_festival_meeting_points_active_order
    ON festival_meeting_points (festival_id, assignment_order, id)
    WHERE status = 'ACTIVE';

ALTER TABLE match_groups
    ADD COLUMN meeting_place_address VARCHAR(500);
