CREATE TABLE match_opponent_exclusions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    lower_member_id BIGINT NOT NULL,
    higher_member_id BIGINT NOT NULL,
    lower_checkin_id BIGINT NOT NULL,
    higher_checkin_id BIGINT NOT NULL,
    rejected_by_member_id BIGINT NOT NULL,
    source_proposal_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_opponent_exclusions PRIMARY KEY (id),
    CONSTRAINT fk_match_opponent_exclusions_lower_member
        FOREIGN KEY (lower_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_opponent_exclusions_higher_member
        FOREIGN KEY (higher_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_opponent_exclusions_lower_checkin
        FOREIGN KEY (lower_checkin_id) REFERENCES festival_checkins (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_opponent_exclusions_higher_checkin
        FOREIGN KEY (higher_checkin_id) REFERENCES festival_checkins (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_opponent_exclusions_rejected_by
        FOREIGN KEY (rejected_by_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_opponent_exclusions_source_proposal
        FOREIGN KEY (source_proposal_id) REFERENCES match_proposals (id) ON DELETE RESTRICT,
    CONSTRAINT chk_match_opponent_exclusions_member_order
        CHECK (lower_member_id < higher_member_id),
    CONSTRAINT chk_match_opponent_exclusions_rejector
        CHECK (rejected_by_member_id IN (lower_member_id, higher_member_id)),
    CONSTRAINT uq_match_opponent_exclusions_checkin_pair
        UNIQUE (lower_checkin_id, higher_checkin_id),
    CONSTRAINT uq_match_opponent_exclusions_source_member_pair
        UNIQUE (source_proposal_id, lower_member_id, higher_member_id)
);

CREATE INDEX idx_match_opponent_exclusions_member_checkin_pair
    ON match_opponent_exclusions (
        lower_member_id, lower_checkin_id, higher_member_id, higher_checkin_id
    );

CREATE INDEX idx_match_opponent_exclusions_higher_member_checkin
    ON match_opponent_exclusions (higher_member_id, higher_checkin_id);

CREATE INDEX idx_match_opponent_exclusions_source_proposal
    ON match_opponent_exclusions (source_proposal_id);
