-- 신고 누적·안전 자동화 (docs/19_ADMIN_MEMBER_SAFETY_ROADMAP.md 4.3)
-- 관리자가 유효하다고 판정한 신고의 penalty/매너온도 적용을 멱등하게 만들고,
-- 유효 신고 누적 임계 도달을 관리자에게 알리는 경량 queue를 추가한다.

ALTER TABLE match_penalty_events
    ADD COLUMN related_report_id BIGINT,
    ADD COLUMN manner_temperature_delta NUMERIC(5,2);

ALTER TABLE match_penalty_events
    ADD CONSTRAINT fk_match_penalty_events_related_report
        FOREIGN KEY (related_report_id) REFERENCES reports (id) ON DELETE RESTRICT;

-- 유효 판정 1건당 penalty event 1건을 강제하는 멱등성 제약.
-- V12의 related_proposal_id, V21의 related_pool_id와 같은 부분 unique index 패턴이다.
CREATE UNIQUE INDEX uq_match_penalty_events_related_report
    ON match_penalty_events (related_report_id)
    WHERE related_report_id IS NOT NULL;

-- 30일 누적 유효 신고 집계용 복합 index
CREATE INDEX idx_reports_reported_member_status_created_at
    ON reports (reported_member_id, status, created_at);

-- 관리자 안전 알림 queue.
-- admin_actions.admin_member_id가 NOT NULL이라 관리자 없이 생성되는 자동 알림을
-- 담을 수 없으므로 별도 table을 사용한다.
CREATE TABLE admin_safety_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reported_member_id BIGINT NOT NULL,
    alert_type VARCHAR(40) NOT NULL,
    trigger_report_id BIGINT NOT NULL,
    valid_report_count INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    handled_admin_id BIGINT,
    handled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_admin_safety_alerts PRIMARY KEY (id),
    CONSTRAINT fk_admin_safety_alerts_member
        FOREIGN KEY (reported_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_admin_safety_alerts_report
        FOREIGN KEY (trigger_report_id) REFERENCES reports (id) ON DELETE RESTRICT,
    CONSTRAINT fk_admin_safety_alerts_admin
        FOREIGN KEY (handled_admin_id) REFERENCES members (id) ON DELETE RESTRICT,
    -- 같은 신고를 다시 유효 판정해도 알림은 1건이다.
    CONSTRAINT uq_admin_safety_alerts_trigger_report UNIQUE (trigger_report_id),
    CONSTRAINT chk_admin_safety_alerts_type CHECK (alert_type IN ('REPORT_THRESHOLD')),
    CONSTRAINT chk_admin_safety_alerts_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'CLOSED')),
    CONSTRAINT chk_admin_safety_alerts_count CHECK (valid_report_count > 0),
    CONSTRAINT chk_admin_safety_alerts_handled CHECK (
        (status = 'OPEN' AND handled_admin_id IS NULL AND handled_at IS NULL)
        OR
        (status <> 'OPEN' AND handled_admin_id IS NOT NULL AND handled_at IS NOT NULL)
    )
);

CREATE INDEX idx_admin_safety_alerts_status_created_at
    ON admin_safety_alerts (status, created_at DESC, id DESC);

CREATE INDEX idx_admin_safety_alerts_member_created_at
    ON admin_safety_alerts (reported_member_id, created_at DESC);
