-- 축제/관광지 찜(북마크)과 공개 댓글·좋아요 테이블을 추가한다.
-- 설계 근거는 docs/27_CONTENT_BOOKMARK_COMMENT_DESIGN.md 3.1~3.4절이다.
--
-- 기존 V1~V25는 수정하지 않는다.
-- 적용 전 공유 dev DB의 flyway_schema_history에서 V26이 비어 있는지 확인한다(docs/27 3.5절).
-- 다른 담당자가 out-of-band로 적용했으면 checksum 충돌이 난다.
--
-- 대상 표현은 target_type + target_id가 아니라 nullable FK 2개 + CHECK다(docs/27 3.1절).
-- recommendation_click_logs가 이미 쓰는 방식이며 FK 참조 정합성을 유지할 수 있다.
-- 단 CHECK는 recommendation_click_logs의 OR(둘 다 채워도 통과) 대신 정확히 하나로 조인다.
-- ON DELETE RESTRICT가 안전한 이유: 축제 동기화는 사라진 축제를 물리 삭제하지 않고
-- FestivalSyncWriter.markMissingFestivalsInactive로 INACTIVE 표시만 한다.

-- 찜. user_blocks와 같은 구조다 - (소유자, 대상) unique pair, created_at만, 해제는 물리 삭제.
CREATE TABLE content_bookmarks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    festival_id BIGINT,
    tour_place_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_content_bookmarks PRIMARY KEY (id),
    CONSTRAINT fk_content_bookmarks_member   FOREIGN KEY (member_id)     REFERENCES members (id)     ON DELETE RESTRICT,
    CONSTRAINT fk_content_bookmarks_festival FOREIGN KEY (festival_id)   REFERENCES festivals (id)   ON DELETE RESTRICT,
    CONSTRAINT fk_content_bookmarks_place    FOREIGN KEY (tour_place_id) REFERENCES tour_places (id) ON DELETE RESTRICT,
    CONSTRAINT chk_content_bookmarks_target
        CHECK ((festival_id IS NOT NULL) <> (tour_place_id IS NOT NULL))
);

-- 두 partial unique index가 동시 요청 중복을 DB에서 흡수한다(docs/27 5.1절).
CREATE UNIQUE INDEX uq_content_bookmarks_member_festival
    ON content_bookmarks (member_id, festival_id) WHERE festival_id IS NOT NULL;
CREATE UNIQUE INDEX uq_content_bookmarks_member_place
    ON content_bookmarks (member_id, tour_place_id) WHERE tour_place_id IS NOT NULL;
CREATE INDEX idx_content_bookmarks_member_created_at
    ON content_bookmarks (member_id, created_at DESC, id DESC);

-- 댓글. deleted_at 단독 soft delete 선례가 없어 status 상태 머신 + 시점 컬럼 관용구를 따른다.
-- status: VISIBLE / DELETED(작성자 삭제) / HIDDEN(관리자 숨김).
-- like_count는 비정규화 카운터이며, content_comment_likes의 실제 영향 행 수가 1일 때만
-- 움직인다(docs/27 2.2절).
CREATE TABLE content_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    festival_id BIGINT,
    tour_place_id BIGINT,
    body VARCHAR(500) NOT NULL,
    like_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'VISIBLE',
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_content_comments PRIMARY KEY (id),
    CONSTRAINT fk_content_comments_member   FOREIGN KEY (member_id)     REFERENCES members (id)     ON DELETE RESTRICT,
    CONSTRAINT fk_content_comments_festival FOREIGN KEY (festival_id)   REFERENCES festivals (id)   ON DELETE RESTRICT,
    CONSTRAINT fk_content_comments_place    FOREIGN KEY (tour_place_id) REFERENCES tour_places (id) ON DELETE RESTRICT,
    CONSTRAINT chk_content_comments_target     CHECK ((festival_id IS NOT NULL) <> (tour_place_id IS NOT NULL)),
    CONSTRAINT chk_content_comments_body       CHECK (char_length(btrim(body)) BETWEEN 1 AND 500),
    CONSTRAINT chk_content_comments_like_count CHECK (like_count >= 0),
    CONSTRAINT chk_content_comments_status     CHECK (status IN ('VISIBLE', 'DELETED', 'HIDDEN')),
    CONSTRAINT chk_content_comments_deleted_at CHECK ((status = 'VISIBLE') = (deleted_at IS NULL))
);

-- 목록 정렬 키는 created_at이 아니라 id DESC다 - 동시 삽입 tie-break가 필요 없고
-- 아래 partial index가 그대로 적중한다(docs/27 3.3절).
CREATE INDEX idx_content_comments_festival_visible ON content_comments (festival_id, id DESC)
    WHERE status = 'VISIBLE' AND festival_id IS NOT NULL;
CREATE INDEX idx_content_comments_place_visible ON content_comments (tour_place_id, id DESC)
    WHERE status = 'VISIBLE' AND tour_place_id IS NOT NULL;
-- 도배 완화 5초 규칙(docs/27 5.2절)과 탈퇴 시 일괄 전환(docs/27 5.7절)이 함께 쓴다.
CREATE INDEX idx_content_comments_member_created_at
    ON content_comments (member_id, created_at DESC, id DESC);

-- 좋아요. uq_content_comment_likes_pair가 멱등성의 근원이고 연타·동시 요청은
-- ON CONFLICT DO NOTHING으로 흡수된다. 자기 댓글 좋아요는 허용한다(docs/27 3.4절).
CREATE TABLE content_comment_likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    comment_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_content_comment_likes PRIMARY KEY (id),
    CONSTRAINT fk_content_comment_likes_comment FOREIGN KEY (comment_id) REFERENCES content_comments (id) ON DELETE RESTRICT,
    CONSTRAINT fk_content_comment_likes_member  FOREIGN KEY (member_id)  REFERENCES members (id)          ON DELETE RESTRICT,
    CONSTRAINT uq_content_comment_likes_pair UNIQUE (comment_id, member_id)
);
CREATE INDEX idx_content_comment_likes_member
    ON content_comment_likes (member_id, created_at DESC, id DESC);
