CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    provider VARCHAR(30) NOT NULL,
    provider_user_id VARCHAR(120) NOT NULL,
    nickname VARCHAR(50),
    profile_image_url VARCHAR(1000),
    gender_encrypted BYTEA,
    age_range_encrypted BYTEA,
    manner_temperature NUMERIC(5,2) NOT NULL DEFAULT 36.50,
    penalty_score INTEGER NOT NULL DEFAULT 0,
    role VARCHAR(30) NOT NULL DEFAULT 'USER',
    status VARCHAR(30) NOT NULL DEFAULT 'PROFILE_REQUIRED',
    last_login_at TIMESTAMPTZ,
    withdrawn_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_members PRIMARY KEY (id),
    CONSTRAINT uq_members_provider_user UNIQUE (provider, provider_user_id),
    CONSTRAINT chk_members_provider CHECK (provider IN ('KAKAO')),
    CONSTRAINT chk_members_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT chk_members_status CHECK (status IN ('ACTIVE', 'PROFILE_REQUIRED', 'SUSPENDED', 'WITHDRAWN', 'DELETED')),
    CONSTRAINT chk_members_manner_temperature CHECK (manner_temperature >= 0 AND manner_temperature <= 100),
    CONSTRAINT chk_members_penalty_score CHECK (penalty_score >= 0)
);

CREATE INDEX idx_members_status ON members (status);
CREATE INDEX idx_members_role ON members (role);
CREATE INDEX idx_members_created_at ON members (created_at);

CREATE TABLE member_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    consent_type VARCHAR(30) NOT NULL,
    version VARCHAR(30) NOT NULL,
    agreed BOOLEAN NOT NULL,
    agreed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_member_consents PRIMARY KEY (id),
    CONSTRAINT fk_member_consents_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT uq_member_consents_member_type_version UNIQUE (member_id, consent_type, version),
    CONSTRAINT chk_member_consents_type CHECK (consent_type IN ('TERMS', 'PRIVACY', 'LOCATION', 'MARKETING')),
    CONSTRAINT chk_member_consents_agreed_at CHECK (
        (agreed = TRUE AND agreed_at IS NOT NULL)
        OR (agreed = FALSE)
    )
);

CREATE INDEX idx_member_consents_member_id ON member_consents (member_id);
CREATE INDEX idx_member_consents_type ON member_consents (consent_type);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT fk_refresh_tokens_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_refresh_tokens_expires_at CHECK (expires_at > created_at)
);

CREATE INDEX idx_refresh_tokens_member_active ON refresh_tokens (member_id, expires_at) WHERE revoked_at IS NULL;
CREATE INDEX idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);

CREATE TABLE festivals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content_id VARCHAR(50) NOT NULL,
    content_type_id VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    address VARCHAR(500),
    area_code VARCHAR(20),
    sigungu_code VARCHAR(20),
    event_start_date DATE,
    event_end_date DATE,
    map_x NUMERIC(13,10),
    map_y NUMERIC(13,10),
    checkin_radius_meters INTEGER NOT NULL DEFAULT 500,
    meeting_radius_meters INTEGER NOT NULL DEFAULT 2000,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    last_synced_at TIMESTAMPTZ,
    raw_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_festivals PRIMARY KEY (id),
    CONSTRAINT uq_festivals_content_id UNIQUE (content_id),
    CONSTRAINT chk_festivals_content_type CHECK (content_type_id = '15'),
    CONSTRAINT chk_festivals_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'ENDED', 'HIDDEN')),
    CONSTRAINT chk_festivals_checkin_radius CHECK (checkin_radius_meters > 0),
    CONSTRAINT chk_festivals_meeting_radius CHECK (meeting_radius_meters > 0),
    CONSTRAINT chk_festivals_event_period CHECK (
        event_start_date IS NULL
        OR event_end_date IS NULL
        OR event_end_date >= event_start_date
    )
);

CREATE INDEX idx_festivals_period ON festivals (event_start_date, event_end_date);
CREATE INDEX idx_festivals_status ON festivals (status);
CREATE INDEX idx_festivals_area ON festivals (area_code, sigungu_code);
CREATE INDEX idx_festivals_content_id ON festivals (content_id);

CREATE TABLE festival_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    festival_id BIGINT NOT NULL,
    origin_image_url VARCHAR(1000) NOT NULL,
    thumbnail_url VARCHAR(1000),
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_festival_images PRIMARY KEY (id),
    CONSTRAINT fk_festival_images_festival FOREIGN KEY (festival_id) REFERENCES festivals (id) ON DELETE RESTRICT,
    CONSTRAINT uq_festival_images_festival_origin UNIQUE (festival_id, origin_image_url),
    CONSTRAINT chk_festival_images_display_order CHECK (display_order >= 0)
);

CREATE INDEX idx_festival_images_festival_order ON festival_images (festival_id, display_order);

CREATE TABLE tour_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content_id VARCHAR(50) NOT NULL,
    content_type_id VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    address VARCHAR(500),
    map_x NUMERIC(13,10),
    map_y NUMERIC(13,10),
    tel VARCHAR(100),
    image_url VARCHAR(1000),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    last_synced_at TIMESTAMPTZ,
    raw_data JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tour_places PRIMARY KEY (id),
    CONSTRAINT uq_tour_places_content_id UNIQUE (content_id),
    CONSTRAINT chk_tour_places_content_type CHECK (content_type_id IN ('12', '14', '28', '39')),
    CONSTRAINT chk_tour_places_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'HIDDEN'))
);

CREATE INDEX idx_tour_places_type_status ON tour_places (content_type_id, status);
CREATE INDEX idx_tour_places_content_id ON tour_places (content_id);

CREATE TABLE tour_api_call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    operation_name VARCHAR(100) NOT NULL,
    request_key VARCHAR(255),
    mobile_app VARCHAR(50) NOT NULL,
    status_code INTEGER,
    success BOOLEAN NOT NULL,
    response_time_ms INTEGER,
    result_count INTEGER,
    error_message VARCHAR(1000),
    called_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_tour_api_call_logs PRIMARY KEY (id),
    CONSTRAINT chk_tour_api_call_logs_mobile_app CHECK (mobile_app = 'SoloIn'),
    CONSTRAINT chk_tour_api_call_logs_response_time CHECK (response_time_ms IS NULL OR response_time_ms >= 0),
    CONSTRAINT chk_tour_api_call_logs_result_count CHECK (result_count IS NULL OR result_count >= 0)
);

CREATE INDEX idx_tour_api_call_logs_operation_called_at ON tour_api_call_logs (operation_name, called_at);
CREATE INDEX idx_tour_api_call_logs_success_called_at ON tour_api_call_logs (success, called_at);

CREATE TABLE festival_checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    festival_id BIGINT NOT NULL,
    distance_meters INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    checked_in_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_festival_checkins PRIMARY KEY (id),
    CONSTRAINT fk_festival_checkins_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_festival_checkins_festival FOREIGN KEY (festival_id) REFERENCES festivals (id) ON DELETE RESTRICT,
    CONSTRAINT chk_festival_checkins_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT chk_festival_checkins_distance CHECK (distance_meters >= 0),
    CONSTRAINT chk_festival_checkins_expires_at CHECK (expires_at > checked_in_at)
);

CREATE UNIQUE INDEX uq_festival_checkins_member_festival_active
    ON festival_checkins (member_id, festival_id)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_festival_checkins_member_active ON festival_checkins (member_id, status, expires_at);
CREATE INDEX idx_festival_checkins_festival_active ON festival_checkins (festival_id, status, expires_at);
CREATE INDEX idx_festival_checkins_expires_at ON festival_checkins (expires_at);
