-- 1:1 문의 센터 테이블을 추가한다.
-- 설계 근거는 docs/28_MEMBER_INQUIRY_DESIGN.md 4절이다.
--
-- 기존 V1~V30은 수정하지 않는다.
--
-- 처음에 V28로 만들었다가 V31로 옮겼다. 협업자가 저장소에 push하지 않은 채 공유 dev DB에
-- V28~V30을 먼저 적용해 두었고, 그 상태에서 이 파일이 V28이면 Flyway가 checksum 충돌로
-- 부팅을 막는다(docs/28 4.1절이 경고한 바로 그 상황이다).
--
-- 적용 전 공유 dev DB의 flyway_schema_history에서 V31이 비어 있는지 반드시 확인한다.
-- 저장소 파일 목록만 보고 번호를 정하면 이 사고가 다시 난다.
--
-- 헤더(inquiries)와 발화(inquiry_messages)를 나눈 이유는 docs/28 3.2절이다. 1테이블로 하면
-- 답변 재작성 시 이전 답변이 UPDATE로 사라지고, 사용자 추가 질문이 새 문의로 쪼개진다.
--
-- 본문은 평문이다(docs/28 3.1절). 비공개 1:1이지만 암호화하면 관리자 키워드 검색이 불가능해지고
-- 이 저장소가 의존하는 char_length CHECK 제약도 걸 수 없다.

-- 문의 스레드 헤더. status는 RECEIVED -> IN_PROGRESS -> ANSWERED -> CLOSED 상태 머신이며
-- CLOSED가 종단이다(docs/28 5.8절).
CREATE TABLE inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    category VARCHAR(30) NOT NULL,
    title VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    -- 긴급 지정은 관리자만 한다. 사용자 등록 요청은 이 값을 받지 않는다(docs/28 확정 5번).
    priority VARCHAR(10) NOT NULL DEFAULT 'NORMAL',
    -- 목록 정렬·badge용 비정규화 값. inquiry_messages INSERT와 같은 transaction에서 갱신한다.
    last_message_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_answered_at TIMESTAMPTZ,
    member_read_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    -- 보관 기간(종결 후 1년) 경과 후 본문을 덮은 시각. 재처리를 막는 원인 key다(docs/28 5.6절).
    anonymized_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_inquiries PRIMARY KEY (id),
    CONSTRAINT fk_inquiries_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    -- SAFETY 카테고리를 두지 않는다. 신고자 보호 제약과 충돌하고 구조화 신고 경로가 이미 있다
    -- (docs/28 3.4절).
    CONSTRAINT chk_inquiries_category CHECK (category IN
        ('SANCTION_APPEAL', 'ACCOUNT', 'MATCHING', 'FESTIVAL_DATA', 'BUG', 'ETC')),
    CONSTRAINT chk_inquiries_status CHECK (status IN
        ('RECEIVED', 'IN_PROGRESS', 'ANSWERED', 'CLOSED')),
    CONSTRAINT chk_inquiries_priority CHECK (priority IN ('NORMAL', 'URGENT')),
    CONSTRAINT chk_inquiries_title CHECK (char_length(btrim(title)) BETWEEN 1 AND 100),
    -- content_comments.chk_content_comments_deleted_at과 같은 관용구다.
    -- 상태와 시점 컬럼을 서로 묶어 DB에서 고정한다.
    CONSTRAINT chk_inquiries_closed_at CHECK ((status = 'CLOSED') = (closed_at IS NOT NULL)),
    -- 답변이 있었던 상태는 last_answered_at이 반드시 있다. CLOSED는 답변 없이 종결될 수 있어
    -- (사용자 자문자답, 중복 문의) 검사에서 제외한다.
    CONSTRAINT chk_inquiries_answered_at CHECK (status <> 'ANSWERED' OR last_answered_at IS NOT NULL),
    CONSTRAINT chk_inquiries_anonymized_at CHECK (anonymized_at IS NULL OR status = 'CLOSED')
);

-- 사용자 "내 문의" 목록. offset 페이징이라 정렬 키를 그대로 담는다(docs/28 5.2절).
CREATE INDEX idx_inquiries_member_created_at ON inquiries (member_id, created_at DESC, id DESC);
-- 관리자 목록. AdminReportRepository와 같은 (created_at DESC, id DESC) 정렬 키다.
CREATE INDEX idx_inquiries_status_created_at ON inquiries (status, created_at DESC, id DESC);
-- 관리자 미처리 조회와 미답변 3건 제한이 함께 쓴다(docs/28 5.1절).
CREATE INDEX idx_inquiries_open ON inquiries (member_id, created_at)
    WHERE status IN ('RECEIVED', 'IN_PROGRESS');
-- 보관 기간 경과 대상 조회. 익명화가 끝난 행은 인덱스에서 빠진다.
CREATE INDEX idx_inquiries_retention ON inquiries (closed_at)
    WHERE status = 'CLOSED' AND anonymized_at IS NULL;

-- 스레드 발화. 사용자 문의와 관리자 답변을 같은 table에 담고 author_type으로 구분한다.
-- author_member_id <> inquiries.member_id로 관리자를 유추하면 관리자가 자기 문의에 답할 때
-- 판정이 깨진다(docs/28 4.3절).
CREATE TABLE inquiry_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    inquiry_id BIGINT NOT NULL,
    author_type VARCHAR(10) NOT NULL,
    author_member_id BIGINT NOT NULL,
    body VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_inquiry_messages PRIMARY KEY (id),
    CONSTRAINT fk_inquiry_messages_inquiry FOREIGN KEY (inquiry_id) REFERENCES inquiries (id) ON DELETE RESTRICT,
    CONSTRAINT fk_inquiry_messages_author FOREIGN KEY (author_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT chk_inquiry_messages_author_type CHECK (author_type IN ('USER', 'ADMIN')),
    CONSTRAINT chk_inquiry_messages_body CHECK (char_length(btrim(body)) BETWEEN 1 AND 2000)
);

-- 스레드 조회는 id 오름차순이다. 동시 삽입 tie-break가 필요 없다.
CREATE INDEX idx_inquiry_messages_inquiry ON inquiry_messages (inquiry_id, id);
-- 4.4 회원 탈퇴 시 일괄 처리용. content_comments의 member 인덱스와 같은 목적이다.
CREATE INDEX idx_inquiry_messages_author_created_at
    ON inquiry_messages (author_member_id, created_at DESC);
