-- 매너온도 상승 이력(docs/19 4.9).
--
-- 지금까지 매너온도는 신고 확정으로만 내려가는 하강 전용 지표였다. 만남 완료 보상과 시간
-- 경과 회복이 생기면서 상승 기록을 남길 곳이 필요하다.
--
-- match_penalty_events에 넣지 않는 이유:
--   1. 그 테이블의 chk_match_penalty_events_score_delta가 score_delta <> 0을 강제한다.
--      온도만 오르고 penalty_score는 그대로인 사건을 표현할 수 없다.
--   2. 이름 그대로 penalty 사건 기록이다. 보상을 섞으면 "제재 이력"을 읽을 수 없게 된다.
--
-- 이 테이블은 상승만 담는다. 하강(REPORT_CONFIRMED)은 기존 match_penalty_events의
-- manner_temperature_delta가 이미 기록하고, 관리자 수동 조정은 admin_actions의
-- MANNER_TEMPERATURE_ADJUST가 기록한다. 기존 두 경로는 건드리지 않는다.
CREATE TABLE manner_temperature_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    -- 상한 clamp 이후 실제로 적용된 상승량. 이미 상한이면 행 자체를 만들지 않는다.
    delta NUMERIC(5,2) NOT NULL,
    before_temperature NUMERIC(5,2) NOT NULL,
    after_temperature NUMERIC(5,2) NOT NULL,
    related_group_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_manner_temperature_events PRIMARY KEY (id),
    CONSTRAINT fk_manner_temperature_events_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_manner_temperature_events_group
        FOREIGN KEY (related_group_id) REFERENCES match_groups (id) ON DELETE RESTRICT,
    CONSTRAINT chk_manner_temperature_events_type CHECK (event_type IN (
        'MATCH_COMPLETED',
        'TIME_RECOVERY'
    )),
    CONSTRAINT chk_manner_temperature_events_delta CHECK (delta > 0),
    -- 만남 완료 보상은 그룹당 회원당 한 번이다. 완료 API를 반복 호출해도 중복 지급되지
    -- 않도록 DB에서 막는다. 애플리케이션 가드만 두면 동시 요청에서 뚫린다.
    CONSTRAINT uq_manner_temperature_events_match_completed
        UNIQUE (member_id, event_type, related_group_id)
);

CREATE INDEX idx_manner_temperature_events_member_created_at
    ON manner_temperature_events (member_id, created_at);

-- 시간 경과 회복 스케줄러가 "마지막 회복 시각"을 찾을 때 쓴다.
CREATE INDEX idx_manner_temperature_events_type_created_at
    ON manner_temperature_events (event_type, created_at);
