-- 슈퍼관리자 ID/PW 로그인 (docs/30)
--
-- SSO를 없애지 않고 진입 경로만 하나 더 만든다. 로그인에 성공하면 OAuth 로그인과
-- 완전히 같은 session(access/refresh cookie)을 발급하므로, 그 뒤의 관리자 API는
-- 코드가 전혀 바뀌지 않는다.
--
-- V36에 이어 붙이지 않고 파일을 나눈 이유: V36은 이미 dev DB에 적용돼 있다. 적용된
-- migration의 내용을 바꾸면 checksum이 달라져 Flyway validate가 실패하고, 되돌리려면
-- 공용 DB에서 history를 손봐야 한다. 적용이 끝난 migration은 수정하지 않는다.

-- 별도 관리자 principal을 만들지 않고 members row 1건에 매핑한다. admin_actions의
-- admin_member_id가 members FK NOT NULL이고 신고 처리·제재·문의 답변이 전부 이 값을
-- 감사 로그로 남기므로, 회원이 아닌 관리자를 만들면 그 경로를 전부 분기해야 한다.
ALTER TABLE members
    DROP CONSTRAINT chk_members_provider;

ALTER TABLE members
    ADD CONSTRAINT chk_members_provider CHECK (provider IN ('KAKAO', 'NAVER', 'LOCAL'));

-- 비밀번호 자격증명. members와 1:1이다.
--
-- members에 컬럼으로 붙이지 않는 이유: 소셜 회원 수만큼 NULL 컬럼 4개가 늘어나고,
-- "비밀번호가 없는 것이 정상"인 행과 "있어야 하는데 없는" 행을 구분할 수 없게 된다.
CREATE TABLE admin_credentials (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id       BIGINT       NOT NULL,
    username        VARCHAR(50)  NOT NULL,
    -- BCrypt 해시만 저장한다. 평문과 가역 암호화를 쓰지 않는다.
    password_hash   VARCHAR(100) NOT NULL,
    failed_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_admin_credentials PRIMARY KEY (id),
    CONSTRAINT uq_admin_credentials_member UNIQUE (member_id),
    CONSTRAINT uq_admin_credentials_username UNIQUE (username),
    CONSTRAINT fk_admin_credentials_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT chk_admin_credentials_failed_attempts CHECK (failed_attempts >= 0)
);

-- 계정 자체는 이 migration에 넣지 않는다. 해시라도 저장소에 커밋되면 docs/06의 Secret
-- 규칙 위반이고, 계정을 바꿀 때마다 migration을 추가해야 한다. 생성과 비밀번호 회전은
-- SuperAdminAccountBootstrap이 환경변수로 처리한다.
