-- 회원 알림함 (docs/32 3.3, docs/19 4.11.5 알림 2단계)
--
-- 1단계는 프론트 전용이었다. 받은 알림을 localStorage에 최근 20건만 남겨서 기기마다 목록이
-- 다르고, 저장소를 지우면 사라지고, 로그인해도 못 본 알림이 복원되지 않았다.
--
-- 번호 주의: 저장소 마지막이 V38이라 V39로 잡았다. 적용 전에 공유 dev DB의
-- flyway_schema_history를 조회해 V39가 비어 있는지 확인한다. 저장소 파일 목록으로 번호를
-- 정했다가 같은 사고가 세 번 났다(docs/10 사고 기록).
CREATE TABLE notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id       BIGINT       NOT NULL,
    -- MatchingStateChangedEvent의 reason과 같은 값. 문구는 프론트가 정한다(notificationMessages.ts).
    reason          VARCHAR(40)  NOT NULL,
    -- 그 변화를 만든 사람. "상대가 도착했어요"를 누른 본인에게 보내지 않으려고 둔다.
    -- 스케줄러가 만든 변화(시간 초과·노쇼)는 행위자가 없어 NULL이다.
    actor_member_id BIGINT,
    occurred_at     TIMESTAMPTZ  NOT NULL,
    read_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_notifications PRIMARY KEY (id),
    -- 알림은 감사 자료가 아니라 소모품이다. 회원 행이 사라지면 함께 지운다.
    -- (실제 탈퇴는 익명화라 행이 남지만, 하드 삭제 시 남겨 둘 이유가 없다.)
    CONSTRAINT fk_notifications_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_actor
        FOREIGN KEY (actor_member_id) REFERENCES members (id) ON DELETE SET NULL
);

-- 목록 조회는 항상 "내 것을 최신순으로"다.
CREATE INDEX idx_notifications_member_created ON notifications (member_id, created_at DESC);

-- 같은 알림을 두 번 쌓지 않는다. 프론트 1단계가 쓰던 중복 방지 키(reason + 발생 시각)와
-- 같은 조합이다. 재시도나 이벤트 중복 발행이 있어도 목록이 어지러워지지 않는다.
CREATE UNIQUE INDEX uq_notifications_member_reason_occurred
    ON notifications (member_id, reason, occurred_at);
