CREATE TABLE user_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    blocker_member_id BIGINT NOT NULL,
    blocked_member_id BIGINT NOT NULL,
    reason VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_blocks PRIMARY KEY (id),
    CONSTRAINT fk_user_blocks_blocker FOREIGN KEY (blocker_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_user_blocks_blocked FOREIGN KEY (blocked_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT uq_user_blocks_pair UNIQUE (blocker_member_id, blocked_member_id),
    CONSTRAINT chk_user_blocks_not_self CHECK (blocker_member_id <> blocked_member_id)
);

CREATE INDEX idx_user_blocks_blocker ON user_blocks (blocker_member_id);
CREATE INDEX idx_user_blocks_blocked ON user_blocks (blocked_member_id);

CREATE TABLE match_pools (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    festival_id BIGINT NOT NULL,
    checkin_id BIGINT NOT NULL,
    preferred_group_size INTEGER NOT NULL,
    allow_minimum_two BOOLEAN NOT NULL DEFAULT FALSE,
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    status VARCHAR(30) NOT NULL DEFAULT 'WAITING',
    entered_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    search_expires_at TIMESTAMPTZ NOT NULL,
    locked_at TIMESTAMPTZ,
    lock_token VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_pools PRIMARY KEY (id),
    CONSTRAINT fk_match_pools_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_pools_festival FOREIGN KEY (festival_id) REFERENCES festivals (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_pools_checkin FOREIGN KEY (checkin_id) REFERENCES festival_checkins (id) ON DELETE RESTRICT,
    CONSTRAINT chk_match_pools_preferred_group_size CHECK (preferred_group_size IN (2, 3, 4)),
    CONSTRAINT chk_match_pools_status CHECK (status IN ('WAITING', 'LOCKED', 'PROPOSED', 'MATCHED', 'EXPIRED', 'CANCELLED', 'COOLDOWN')),
    CONSTRAINT chk_match_pools_search_expires_at CHECK (search_expires_at > entered_at)
);

CREATE UNIQUE INDEX uq_match_pools_member_active
    ON match_pools (member_id)
    WHERE status IN ('WAITING', 'LOCKED', 'PROPOSED');

CREATE INDEX idx_match_pools_festival_status_expires ON match_pools (festival_id, status, search_expires_at);
CREATE INDEX idx_match_pools_member_status ON match_pools (member_id, status);
CREATE INDEX idx_match_pools_locked_at ON match_pools (locked_at);

CREATE TABLE match_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    festival_id BIGINT NOT NULL,
    target_group_size INTEGER NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'CREATED',
    score NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_by VARCHAR(30) NOT NULL DEFAULT 'SCHEDULER',
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    confirmed_at TIMESTAMPTZ,
    failed_reason VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_attempts PRIMARY KEY (id),
    CONSTRAINT fk_match_attempts_festival FOREIGN KEY (festival_id) REFERENCES festivals (id) ON DELETE RESTRICT,
    CONSTRAINT chk_match_attempts_target_group_size CHECK (target_group_size IN (2, 3, 4)),
    CONSTRAINT chk_match_attempts_status CHECK (status IN ('CREATED', 'PROPOSING', 'WAITING_RESPONSES', 'INSUFFICIENT_MEMBERS', 'CONFIRMED', 'FAILED', 'CANCELLED', 'EXPIRED')),
    CONSTRAINT chk_match_attempts_score CHECK (score >= 0),
    CONSTRAINT chk_match_attempts_created_by CHECK (created_by IN ('SCHEDULER', 'POOL_ENTRY')),
    CONSTRAINT chk_match_attempts_expires_at CHECK (expires_at > started_at)
);

CREATE INDEX idx_match_attempts_festival_status ON match_attempts (festival_id, status);
CREATE INDEX idx_match_attempts_expires_at ON match_attempts (expires_at);
CREATE INDEX idx_match_attempts_status_created_at ON match_attempts (status, created_at);

CREATE TABLE match_attempt_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attempt_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    pool_id BIGINT NOT NULL,
    member_score NUMERIC(10,2) NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'CANDIDATE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_attempt_members PRIMARY KEY (id),
    CONSTRAINT fk_match_attempt_members_attempt FOREIGN KEY (attempt_id) REFERENCES match_attempts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_attempt_members_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_attempt_members_pool FOREIGN KEY (pool_id) REFERENCES match_pools (id) ON DELETE RESTRICT,
    CONSTRAINT uq_match_attempt_members_attempt_member UNIQUE (attempt_id, member_id),
    CONSTRAINT uq_match_attempt_members_attempt_pool UNIQUE (attempt_id, pool_id),
    CONSTRAINT chk_match_attempt_members_status CHECK (status IN ('CANDIDATE', 'PROPOSED', 'ACCEPTED', 'REJECTED', 'TIMEOUT', 'EXCLUDED')),
    CONSTRAINT chk_match_attempt_members_score CHECK (member_score >= 0)
);

CREATE INDEX idx_match_attempt_members_member ON match_attempt_members (member_id);
CREATE INDEX idx_match_attempt_members_attempt_status ON match_attempt_members (attempt_id, status);

CREATE TABLE match_proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attempt_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'SENT',
    sent_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    responded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_proposals PRIMARY KEY (id),
    CONSTRAINT fk_match_proposals_attempt FOREIGN KEY (attempt_id) REFERENCES match_attempts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_proposals_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT uq_match_proposals_attempt_member UNIQUE (attempt_id, member_id),
    CONSTRAINT chk_match_proposals_status CHECK (status IN ('SENT', 'ACCEPTED', 'REJECTED', 'TIMEOUT', 'EXPIRED')),
    CONSTRAINT chk_match_proposals_expires_at CHECK (expires_at > sent_at),
    CONSTRAINT chk_match_proposals_responded_at CHECK (responded_at IS NULL OR responded_at >= sent_at)
);

CREATE INDEX idx_match_proposals_member_status ON match_proposals (member_id, status);
CREATE INDEX idx_match_proposals_expires_status ON match_proposals (expires_at, status);
CREATE INDEX idx_match_proposals_attempt_status ON match_proposals (attempt_id, status);

CREATE TABLE match_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    proposal_id BIGINT NOT NULL,
    attempt_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    response VARCHAR(40) NOT NULL,
    responded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_responses PRIMARY KEY (id),
    CONSTRAINT fk_match_responses_proposal FOREIGN KEY (proposal_id) REFERENCES match_proposals (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_responses_attempt FOREIGN KEY (attempt_id) REFERENCES match_attempts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_responses_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT uq_match_responses_proposal_member UNIQUE (proposal_id, member_id),
    CONSTRAINT chk_match_responses_response CHECK (response IN ('ACCEPTED', 'REJECTED', 'TIMEOUT', 'START_WITH_CURRENT_MEMBERS', 'CANCEL_CURRENT_MEMBERS'))
);

CREATE INDEX idx_match_responses_attempt_response ON match_responses (attempt_id, response);
CREATE INDEX idx_match_responses_member_created_at ON match_responses (member_id, created_at);

CREATE TABLE match_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    attempt_id BIGINT NOT NULL,
    festival_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'CONFIRMED',
    confirmed_member_count INTEGER NOT NULL,
    meeting_place_name VARCHAR(255),
    meeting_place_content_id VARCHAR(50),
    meeting_map_x NUMERIC(13,10),
    meeting_map_y NUMERIC(13,10),
    confirmed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_groups PRIMARY KEY (id),
    CONSTRAINT fk_match_groups_attempt FOREIGN KEY (attempt_id) REFERENCES match_attempts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_groups_festival FOREIGN KEY (festival_id) REFERENCES festivals (id) ON DELETE RESTRICT,
    CONSTRAINT uq_match_groups_attempt UNIQUE (attempt_id),
    CONSTRAINT chk_match_groups_status CHECK (status IN ('CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT chk_match_groups_confirmed_member_count CHECK (confirmed_member_count BETWEEN 2 AND 4)
);

CREATE INDEX idx_match_groups_festival_status ON match_groups (festival_id, status);
CREATE INDEX idx_match_groups_status_confirmed_at ON match_groups (status, confirmed_at);

CREATE TABLE match_group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'JOINED',
    arrival_minutes INTEGER,
    arrival_time_selected_at TIMESTAMPTZ,
    arrived_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    cancel_reason VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_group_members PRIMARY KEY (id),
    CONSTRAINT fk_match_group_members_group FOREIGN KEY (group_id) REFERENCES match_groups (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_group_members_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT uq_match_group_members_group_member UNIQUE (group_id, member_id),
    CONSTRAINT chk_match_group_members_status CHECK (status IN ('JOINED', 'ARRIVAL_TIME_SELECTED', 'ARRIVED', 'CANCELLED', 'NO_SHOW', 'LEFT')),
    CONSTRAINT chk_match_group_members_arrival_minutes CHECK (arrival_minutes IS NULL OR arrival_minutes IN (0, 5, 10, 20, 30))
);

CREATE UNIQUE INDEX uq_match_group_members_member_active
    ON match_group_members (member_id)
    WHERE status IN ('JOINED', 'ARRIVAL_TIME_SELECTED', 'ARRIVED');

CREATE INDEX idx_match_group_members_member_status ON match_group_members (member_id, status);
CREATE INDEX idx_match_group_members_group_status ON match_group_members (group_id, status);

CREATE TABLE match_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id BIGINT,
    attempt_id BIGINT,
    member_id BIGINT,
    event_type VARCHAR(60) NOT NULL,
    payload JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_events PRIMARY KEY (id),
    CONSTRAINT fk_match_events_group FOREIGN KEY (group_id) REFERENCES match_groups (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_events_attempt FOREIGN KEY (attempt_id) REFERENCES match_attempts (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_events_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT chk_match_events_type CHECK (event_type IN (
        'MATCH_PROPOSED',
        'MATCH_ACCEPTED',
        'MATCH_REJECTED',
        'MATCH_TIMEOUT',
        'MATCH_INSUFFICIENT_MEMBERS',
        'MATCH_CONFIRMED',
        'ARRIVAL_TIME_SELECTED',
        'MEMBER_ARRIVED',
        'MEMBER_CANCELLED',
        'MATCH_CANCELLED',
        'SAFETY_REMINDER'
    ))
);

CREATE INDEX idx_match_events_group_created_at ON match_events (group_id, created_at);
CREATE INDEX idx_match_events_attempt_created_at ON match_events (attempt_id, created_at);
CREATE INDEX idx_match_events_member_created_at ON match_events (member_id, created_at);
CREATE INDEX idx_match_events_type_created_at ON match_events (event_type, created_at);

CREATE TABLE match_cooldowns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    reason VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    starts_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_cooldowns PRIMARY KEY (id),
    CONSTRAINT fk_match_cooldowns_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT chk_match_cooldowns_reason CHECK (reason IN ('REJECT', 'TIMEOUT', 'CANCEL', 'NO_SHOW', 'REPORT')),
    CONSTRAINT chk_match_cooldowns_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT chk_match_cooldowns_expires_at CHECK (expires_at > starts_at)
);

CREATE UNIQUE INDEX uq_match_cooldowns_member_active
    ON match_cooldowns (member_id)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_match_cooldowns_member_expires ON match_cooldowns (member_id, expires_at);
CREATE INDEX idx_match_cooldowns_expires_at ON match_cooldowns (expires_at);

CREATE TABLE match_penalty_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    event_type VARCHAR(40) NOT NULL,
    score_delta INTEGER NOT NULL,
    reason VARCHAR(255),
    related_group_id BIGINT,
    related_attempt_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_penalty_events PRIMARY KEY (id),
    CONSTRAINT fk_match_penalty_events_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_penalty_events_group FOREIGN KEY (related_group_id) REFERENCES match_groups (id) ON DELETE RESTRICT,
    CONSTRAINT fk_match_penalty_events_attempt FOREIGN KEY (related_attempt_id) REFERENCES match_attempts (id) ON DELETE RESTRICT,
    CONSTRAINT chk_match_penalty_events_type CHECK (event_type IN ('TIMEOUT', 'CANCEL', 'NO_SHOW', 'REPORT_CONFIRMED', 'DECAY', 'ADMIN_ADJUST')),
    CONSTRAINT chk_match_penalty_events_score_delta CHECK (score_delta <> 0)
);

CREATE INDEX idx_match_penalty_events_member_created_at ON match_penalty_events (member_id, created_at);
CREATE INDEX idx_match_penalty_events_type_created_at ON match_penalty_events (event_type, created_at);
