-- Web Push 구독 (docs/32 3.4, docs/19 4.11.5 알림 3단계)
--
-- 앱이 꺼져 있어도 알림이 가야 하는 이유는 MATCH_PROPOSED다. 응답 시간이 30초이고 놓치면
-- penalty_score +1에 쿨타임 2분이 붙는다. WebSocket은 화면이 열려 있을 때만 닿는다.
--
-- 번호 주의: V39(알림함) 다음이다. 적용 전에 공유 dev DB의 flyway_schema_history를 조회해
-- 그 번호가 비어 있는지 확인한다(docs/10 사고 기록 — 저장소 파일 목록으로 정하지 않는다).
CREATE TABLE push_subscriptions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id   BIGINT       NOT NULL,
    -- 브라우저가 발급하는 push 서비스 주소. 이것이 구독의 신원이다.
    endpoint    VARCHAR(500) NOT NULL,
    -- 발송 암호화 키. 서버는 이 값으로만 내용을 암호화할 수 있고 복호화는 브라우저가 한다.
    p256dh      VARCHAR(255) NOT NULL,
    auth        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_push_subscriptions PRIMARY KEY (id),
    -- 같은 브라우저가 다시 구독하면 새 행을 만들지 않고 주인을 바꾼다. 한 기기를 두 계정이
    -- 쓰는 경우(로그아웃 후 다른 계정 로그인)에 예전 주인에게 알림이 가면 안 된다.
    CONSTRAINT uq_push_subscriptions_endpoint UNIQUE (endpoint),
    CONSTRAINT fk_push_subscriptions_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE
);

-- 발송은 항상 "이 회원의 구독 전부"를 찾는다.
CREATE INDEX idx_push_subscriptions_member ON push_subscriptions (member_id);
