-- 매칭 후보 수집 구간(collection window)
--
-- 왜 필요한가
--   scheduler tick마다 "지금 대기 중인 후보 전체"를 평가하면, 유효한 조합이 처음 생기는 순간
--   소진돼 대기 후보가 2명을 넘지 못한다. 조합이 1개뿐이면 정렬해서 고를 대상이 없으므로
--   궁합 점수가 순위에 개입하지 못하고 먼저 신청한 사람끼리 묶인다(docs/10, docs/32 항목 G).
--   그래서 "같은 축제의 첫 유효 대기자가 들어온 시점부터 N초"를 하나의 구간으로 두고,
--   그 구간이 끝난 뒤 모인 후보를 한 번에 평가한다.
--
-- 왜 유도하지 않고 저장하는가
--   후보의 MIN(entered_at)으로 구간을 유도하면 첫 신청자가 취소·매칭·만료될 때 시작점이
--   바뀌어 종료 시각이 움직인다. A(0초)·B(2초)에서 A가 5초에 취소하면 [0,10)이 [2,12)로
--   밀린다. 한 번 정해진 구간은 고정돼야 하므로 행으로 남긴다.
--
-- 상태를 넷으로 나눈 이유
--   수집 종료와 평가 완료는 다른 사건이다. 둘을 한 상태로 합치면, 신규 신청이 만료된 구간을
--   닫아버렸을 때 scheduler가 그 구간을 더 이상 조회하지 않아 평가가 통째로 누락된다.
--     OPEN        수집 중
--     COLLECTED   수집 종료, 평가 대기      ← 신청 경로가 내리는 상태
--     EVALUATING  한 실행이 소유하고 평가 중
--     EVALUATED   평가 완료(또는 유효 후보 0건으로 종결)
--   scheduler는 (OPEN, COLLECTED) 중 ends_at이 지난 것을 집으므로 누락되지 않는다.

CREATE TABLE match_collection_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    festival_id BIGINT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    -- 평가 소유권. DB 행 잠금은 claim 트랜잭션이 끝나면 풀리므로, 평가가 끝날 때까지의
    -- 소유는 match_pools.lock_token과 같은 방식으로 토큰 임대(lease)로 표시한다.
    evaluator_token VARCHAR(100),
    evaluation_started_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_match_collection_windows PRIMARY KEY (id),
    CONSTRAINT fk_match_collection_windows_festival
        FOREIGN KEY (festival_id) REFERENCES festivals (id) ON DELETE RESTRICT,
    CONSTRAINT chk_match_collection_windows_status
        CHECK (status IN ('OPEN', 'COLLECTED', 'EVALUATING', 'EVALUATED')),
    CONSTRAINT chk_match_collection_windows_period
        CHECK (ends_at > started_at),
    -- 평가 중일 때만 소유 정보가 있다. 상태와 소유 정보가 어긋나지 않도록 강제한다.
    CONSTRAINT chk_match_collection_windows_evaluator
        CHECK (
            (status = 'EVALUATING')
            = (evaluator_token IS NOT NULL AND evaluation_started_at IS NOT NULL)
        )
);

-- 축제당 열린 구간은 하나뿐이다.
--
-- 부분 unique 인덱스로 DB가 직접 막는다. 신청이 동시에 들어와 둘 다 "열린 구간 없음"을 보고
-- 생성하려 해도 한쪽만 성공한다. 애플리케이션은 INSERT ... ON CONFLICT DO NOTHING 후 재조회로
-- 기존 구간에 합류하므로, 경쟁에서 진 신청이 예외로 실패하지 않는다.
-- COLLECTED/EVALUATING/EVALUATED는 이 인덱스에 걸리지 않으므로 다음 구간 생성을 막지 않는다.
CREATE UNIQUE INDEX uq_match_collection_windows_open_festival
    ON match_collection_windows (festival_id)
    WHERE status = 'OPEN';

-- scheduler가 "닫을 구간"을 찾는 경로.
CREATE INDEX idx_match_collection_windows_pending
    ON match_collection_windows (ends_at)
    WHERE status IN ('OPEN', 'COLLECTED');

-- 평가 중 장애로 EVALUATING에 남은 구간을 회수하는 경로.
CREATE INDEX idx_match_collection_windows_evaluating
    ON match_collection_windows (evaluation_started_at)
    WHERE status = 'EVALUATING';

-- 후보가 어느 구간에 속하는지.
--
-- NULL을 허용한다. 배포 시점에 이미 대기 중이던 pool에는 구간이 없고, 그 행들은 다음 tick이
-- 해당 축제의 열린 구간으로 편입한다. 잔여 후보는 다음 구간으로 이 값만 옮기며
-- entered_at과 search_expires_at은 그대로 둔다.
ALTER TABLE match_pools
    ADD COLUMN collect_window_id BIGINT;

ALTER TABLE match_pools
    ADD CONSTRAINT fk_match_pools_collect_window
        FOREIGN KEY (collect_window_id) REFERENCES match_collection_windows (id) ON DELETE SET NULL;

-- 구간 단위로 후보를 전량 조회한다. batchSize로 신청순을 자르지 않기 위한 인덱스다.
CREATE INDEX idx_match_pools_collect_window
    ON match_pools (collect_window_id, entered_at, id)
    WHERE status = 'WAITING';

COMMENT ON TABLE match_collection_windows IS '매칭 후보 수집 구간. 축제별로 독립이며 ends_at은 생성 후 변경하지 않는다.';
COMMENT ON COLUMN match_collection_windows.status IS 'OPEN 수집 중 / COLLECTED 수집 종료·평가 대기 / EVALUATING 평가 중 / EVALUATED 종결';
COMMENT ON COLUMN match_collection_windows.evaluator_token IS '평가를 소유한 실행의 토큰. match_pools.lock_token과 같은 값을 쓴다.';
COMMENT ON COLUMN match_pools.collect_window_id IS '이 후보가 속한 수집 구간. 잔여 후보는 다음 구간으로 옮겨진다.';
