CREATE TABLE member_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_id BIGINT NOT NULL,
    reviewer_member_id BIGINT NOT NULL,
    reviewee_member_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    manner_delta NUMERIC(5,2) NOT NULL DEFAULT 0,
    review_tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    comment_encrypted BYTEA,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_member_reviews PRIMARY KEY (id),
    CONSTRAINT fk_member_reviews_group FOREIGN KEY (group_id) REFERENCES match_groups (id) ON DELETE RESTRICT,
    CONSTRAINT fk_member_reviews_reviewer FOREIGN KEY (reviewer_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_member_reviews_reviewee FOREIGN KEY (reviewee_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT uq_member_reviews_group_reviewer_reviewee UNIQUE (group_id, reviewer_member_id, reviewee_member_id),
    CONSTRAINT chk_member_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT chk_member_reviews_not_self CHECK (reviewer_member_id <> reviewee_member_id)
);

CREATE INDEX idx_member_reviews_reviewee_created_at ON member_reviews (reviewee_member_id, created_at);
CREATE INDEX idx_member_reviews_group ON member_reviews (group_id);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reporter_member_id BIGINT NOT NULL,
    reported_member_id BIGINT NOT NULL,
    group_id BIGINT,
    reason_code VARCHAR(40) NOT NULL,
    detail_encrypted BYTEA,
    status VARCHAR(30) NOT NULL DEFAULT 'SUBMITTED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT pk_reports PRIMARY KEY (id),
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reports_reported FOREIGN KEY (reported_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reports_group FOREIGN KEY (group_id) REFERENCES match_groups (id) ON DELETE RESTRICT,
    CONSTRAINT uq_reports_reporter_reported_group_reason UNIQUE (reporter_member_id, reported_member_id, group_id, reason_code),
    CONSTRAINT chk_reports_not_self CHECK (reporter_member_id <> reported_member_id),
    CONSTRAINT chk_reports_reason_code CHECK (reason_code IN ('RUDE', 'SEXUAL_HARASSMENT', 'NO_SHOW', 'SCAM', 'SAFETY', 'OTHER')),
    CONSTRAINT chk_reports_status CHECK (status IN ('SUBMITTED', 'REVIEWING', 'RESOLVED', 'REJECTED', 'ACTION_TAKEN'))
);

CREATE INDEX idx_reports_status_created_at ON reports (status, created_at);
CREATE INDEX idx_reports_reported_member ON reports (reported_member_id);
CREATE INDEX idx_reports_reporter_member ON reports (reporter_member_id);

CREATE TABLE admin_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    admin_member_id BIGINT NOT NULL,
    target_member_id BIGINT,
    report_id BIGINT,
    action_type VARCHAR(40) NOT NULL,
    reason VARCHAR(500),
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_admin_actions PRIMARY KEY (id),
    CONSTRAINT fk_admin_actions_admin FOREIGN KEY (admin_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_admin_actions_target FOREIGN KEY (target_member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_admin_actions_report FOREIGN KEY (report_id) REFERENCES reports (id) ON DELETE RESTRICT,
    CONSTRAINT chk_admin_actions_type CHECK (action_type IN (
        'WARNING',
        'SUSPEND',
        'BAN',
        'UNBAN',
        'REPORT_RESOLVE',
        'REPORT_REJECT',
        'MANUAL_PENALTY',
        'DATA_CORRECTION'
    ))
);

CREATE INDEX idx_admin_actions_admin_created_at ON admin_actions (admin_member_id, created_at);
CREATE INDEX idx_admin_actions_target_created_at ON admin_actions (target_member_id, created_at);
CREATE INDEX idx_admin_actions_report ON admin_actions (report_id);

CREATE TABLE solo_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    festival_id BIGINT NOT NULL,
    source_attempt_id BIGINT,
    title VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_solo_courses PRIMARY KEY (id),
    CONSTRAINT fk_solo_courses_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_solo_courses_festival FOREIGN KEY (festival_id) REFERENCES festivals (id) ON DELETE RESTRICT,
    CONSTRAINT fk_solo_courses_source_attempt FOREIGN KEY (source_attempt_id) REFERENCES match_attempts (id) ON DELETE RESTRICT,
    CONSTRAINT chk_solo_courses_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'DISMISSED')),
    CONSTRAINT chk_solo_courses_expires_at CHECK (expires_at > created_at)
);

CREATE INDEX idx_solo_courses_member_status ON solo_courses (member_id, status);
CREATE INDEX idx_solo_courses_festival_created_at ON solo_courses (festival_id, created_at);

CREATE TABLE solo_course_places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    solo_course_id BIGINT NOT NULL,
    tour_place_id BIGINT NOT NULL,
    display_order INTEGER NOT NULL,
    recommendation_reason VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_solo_course_places PRIMARY KEY (id),
    CONSTRAINT fk_solo_course_places_course FOREIGN KEY (solo_course_id) REFERENCES solo_courses (id) ON DELETE RESTRICT,
    CONSTRAINT fk_solo_course_places_place FOREIGN KEY (tour_place_id) REFERENCES tour_places (id) ON DELETE RESTRICT,
    CONSTRAINT uq_solo_course_places_course_order UNIQUE (solo_course_id, display_order),
    CONSTRAINT uq_solo_course_places_course_place UNIQUE (solo_course_id, tour_place_id),
    CONSTRAINT chk_solo_course_places_display_order CHECK (display_order > 0)
);

CREATE INDEX idx_solo_course_places_course_order ON solo_course_places (solo_course_id, display_order);

CREATE TABLE recommendation_click_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    festival_id BIGINT,
    tour_place_id BIGINT,
    solo_course_id BIGINT,
    source VARCHAR(40) NOT NULL,
    clicked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_recommendation_click_logs PRIMARY KEY (id),
    CONSTRAINT fk_recommendation_click_logs_member FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recommendation_click_logs_festival FOREIGN KEY (festival_id) REFERENCES festivals (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recommendation_click_logs_place FOREIGN KEY (tour_place_id) REFERENCES tour_places (id) ON DELETE RESTRICT,
    CONSTRAINT fk_recommendation_click_logs_course FOREIGN KEY (solo_course_id) REFERENCES solo_courses (id) ON DELETE RESTRICT,
    CONSTRAINT chk_recommendation_click_logs_source CHECK (source IN ('MATCH_FAILED', 'MATCH_ROOM', 'SOLO_COURSE', 'FESTIVAL_DETAIL')),
    CONSTRAINT chk_recommendation_click_logs_target CHECK (tour_place_id IS NOT NULL OR solo_course_id IS NOT NULL)
);

CREATE INDEX idx_recommendation_click_logs_member_clicked_at ON recommendation_click_logs (member_id, clicked_at);
CREATE INDEX idx_recommendation_click_logs_festival_clicked_at ON recommendation_click_logs (festival_id, clicked_at);
CREATE INDEX idx_recommendation_click_logs_source_clicked_at ON recommendation_click_logs (source, clicked_at);
