CREATE TABLE member_travel_styles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    style_code VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_member_travel_styles PRIMARY KEY (id),
    CONSTRAINT fk_member_travel_styles_member
        FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE RESTRICT,
    CONSTRAINT uq_member_travel_styles_member_style UNIQUE (member_id, style_code),
    CONSTRAINT chk_member_travel_styles_style_code
        CHECK (style_code IN ('RELAXED', 'ACTIVE', 'FOOD', 'PHOTO', 'CULTURE'))
);

CREATE INDEX idx_member_travel_styles_member_id ON member_travel_styles (member_id);
