import { useEffect, useRef, useState, type RefObject } from 'react';
import { ChevronLeft, ChevronRight, X } from 'lucide-react';
import AdminHeader from '../components/admin/AdminHeader';
import AdminNav from '../components/admin/AdminNav';
import type { AdminMemberActionReasonCode, AdminMemberActionRequest, AdminMemberActionType, AdminMemberDetail, AdminMemberFilters, AdminSuspensionDuration } from '../api/adminMembers';
import { EMPTY_ADMIN_MEMBER_FILTERS, useAdminMembers } from '../hooks/useAdminMembers';
import { formatSeoulDateTime } from '../utils/dateTime';
import { LoadingState } from '../components/common/Spinner';

const statusLabel: Record<string, string> = { ACTIVE: '활성', PROFILE_REQUIRED: '프로필 필요', SUSPENDED: '이용정지', BANNED: '블랙리스트', WITHDRAWN: '탈퇴', DELETED: '삭제' };
const actionLabel: Record<AdminMemberActionType, string> = { WARNING: '경고', SUSPEND: '이용정지', BAN: '영구차단', UNBAN: '차단 해제', UNSUSPEND: '정지 해제' };

export default function AdminMembersPage() {
  const { state, reload, applyFilters, next, previous, openDetail, closeDetail, requestAction, cancelAction, submitAction } = useAdminMembers();
  const [draft, setDraft] = useState<AdminMemberFilters>(EMPTY_ADMIN_MEMBER_FILTERS);
  return <div className="min-h-screen bg-sand"><AdminHeader title="회원 조회·제재" /><AdminNav /><main className="mx-auto max-w-5xl p-6">
    <form onSubmit={(event) => { event.preventDefault(); void applyFilters(draft); }} className="grid gap-3 rounded-2xl bg-white p-4 sm:grid-cols-4"><input aria-label="닉네임 검색" value={draft.query} maxLength={50} onChange={(event) => setDraft({ ...draft, query: event.target.value })} placeholder="닉네임 검색" className="rounded-xl border border-line px-3 py-2"/><select aria-label="회원 상태" value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as AdminMemberFilters['status'] })} className="rounded-xl border border-line px-3 py-2"><option value="">전체 상태</option>{Object.entries(statusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="회원 역할" value={draft.role} onChange={(event) => setDraft({ ...draft, role: event.target.value as AdminMemberFilters['role'] })} className="rounded-xl border border-line px-3 py-2"><option value="">전체 역할</option><option value="USER">USER</option><option value="ADMIN">ADMIN</option></select><button className="rounded-xl bg-coral px-4 py-2 font-bold text-white">검색</button></form>
    {state.status === 'LOADING' && <LoadingState message="회원을 불러오는 중이에요" />}{state.status === 'ERROR' && <div role="alert" className="p-8 text-center"><p>회원 목록을 불러오지 못했습니다.</p><button onClick={() => void reload()} className="mt-2 underline">다시 시도</button></div>}{state.status === 'READY' && state.items.length === 0 && <p className="p-8 text-center">조건에 맞는 회원이 없습니다.</p>}
    {state.status === 'READY' && state.items.length > 0 && <div className="mt-4 overflow-hidden rounded-2xl bg-white">{state.items.map((member) => <button type="button" key={member.memberId} onClick={() => void openDetail(member.memberId)} className="flex w-full items-center gap-4 border-b border-line p-4 text-left last:border-0"><div className="flex-1"><p className="font-bold">{member.nickname ?? '닉네임 없음'}</p><p className="text-sm text-ink/50">{member.role} · {statusLabel[member.status]}</p></div><div className="text-right text-sm"><p>패널티 {member.penaltyScore}</p><p>매너 {member.mannerTemperature.toFixed(2)}</p>{member.suspendedUntil && <p className="text-coral">~ {formatSeoulDateTime(member.suspendedUntil)}</p>}</div><ChevronRight size={18}/></button>)}</div>}
    <div className="mt-4 flex items-center justify-center gap-3"><button disabled={state.pageIndex === 0 || state.status === 'LOADING'} onClick={() => void previous()} className="rounded-xl border border-line bg-white p-2 disabled:opacity-40"><ChevronLeft/></button><span>{state.pageIndex + 1} 페이지</span><button disabled={!state.hasNext || state.status === 'LOADING'} onClick={() => void next()} className="rounded-xl border border-line bg-white p-2 disabled:opacity-40"><ChevronRight/></button></div>
  </main>{state.selectedMemberId !== null && <AdminMemberDetailDialog detail={state.detail} loading={state.detailLoading} error={state.detailError} onClose={closeDetail} onAction={(action) => state.detail && requestAction(defaultActionRequest(state.detail, action))}/>} {state.detail && state.pendingAction && <AdminMemberActionDialog detail={state.detail} initial={state.pendingAction} submitting={state.submitting} error={state.actionError} onClose={cancelAction} onSubmit={(request) => { requestAction(request); queueMicrotask(() => void submitAction()); }}/>}</div>;
}

function defaultActionRequest(detail: AdminMemberDetail, action: AdminMemberActionType): AdminMemberActionRequest {
  return { action, reasonCode: action === 'UNSUSPEND' ? 'ADMIN_CORRECTION' : 'COMMUNITY_GUIDELINE', reasonNote: null, suspensionDuration: action === 'SUSPEND' ? 'SEVEN_DAYS' : null, reportId: null, expectedStatus: detail.status };
}

export function AdminMemberDetailDialog({ detail, loading, error, onClose, onAction }: { detail: AdminMemberDetail | null; loading: boolean; error: Error | null; onClose: () => void; onAction: (action: AdminMemberActionType) => void }) {
  return <div className="fixed inset-0 z-40 flex items-center justify-center bg-ink/55 p-4"><section role="dialog" aria-modal="true" aria-labelledby="member-detail-title" className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6"><div className="flex justify-between"><h2 id="member-detail-title" className="text-lg font-bold">회원 상세</h2><button onClick={onClose} aria-label="회원 상세 닫기"><X/></button></div>{loading && <LoadingState className="mt-4" message="상세 정보를 불러오는 중이에요" />}{error && <p role="alert" className="mt-4 text-coral">상세 정보를 불러오지 못했습니다.</p>}{detail && <><dl className="mt-4 grid grid-cols-[auto_1fr] gap-3 text-sm"><dt>닉네임</dt><dd className="text-right font-bold">{detail.nickname ?? '없음'}</dd><dt>상태</dt><dd className="text-right">{statusLabel[detail.status]}</dd><dt>패널티 점수</dt><dd className="text-right">{detail.penaltyScore}</dd><dt>매너온도</dt><dd className="text-right">{detail.mannerTemperature.toFixed(2)}</dd><dt>30일 유효 신고</dt><dd className="text-right">{detail.recentValidReportCount}건{detail.safetyReviewRequired && <span className="ml-2 rounded-full bg-coral px-2 py-0.5 text-xs font-bold text-white">이용 제한 검토 대상</span>}</dd>{detail.suspendedUntil && <><dt>정지 종료</dt><dd className="text-right">{formatSeoulDateTime(detail.suspendedUntil)}</dd></>}</dl><section className="mt-5"><h3 className="font-bold">피신고 이력</h3>{detail.reports.length === 0 ? <p className="text-sm text-ink/50">없음</p> : detail.reports.map((report) => <p key={report.reportId} className="mt-2 text-sm">{report.reasonCode} · {report.status} · {formatSeoulDateTime(report.createdAt)}</p>)}</section><section className="mt-5"><h3 className="font-bold">제재 이력</h3>{detail.actions.length === 0 ? <p className="text-sm text-ink/50">없음</p> : detail.actions.map((action) => <p key={action.actionId} className="mt-2 text-sm">{actionLabel[action.actionType]} · {action.reasonCode} · {formatSeoulDateTime(action.createdAt)}</p>)}</section>{detail.role === 'USER' && <div className="mt-6 flex flex-wrap justify-end gap-2">{detail.status !== 'BANNED' && <button onClick={() => onAction('WARNING')} className="rounded-xl border border-line px-4 py-2">경고</button>}{(detail.status === 'ACTIVE' || detail.status === 'PROFILE_REQUIRED') && <button onClick={() => onAction('SUSPEND')} className="rounded-xl border border-coral px-4 py-2 text-coral">이용정지</button>}{['ACTIVE','PROFILE_REQUIRED','SUSPENDED'].includes(detail.status) && <button onClick={() => onAction('BAN')} className="rounded-xl bg-coral px-4 py-2 font-bold text-white">영구차단</button>}{detail.status === 'SUSPENDED' && <button onClick={() => onAction('UNSUSPEND')} className="rounded-xl bg-teal px-4 py-2 font-bold text-white">정지 해제</button>}{detail.status === 'BANNED' && <button onClick={() => onAction('UNBAN')} className="rounded-xl bg-teal px-4 py-2 font-bold text-white">차단 해제</button>}</div>}</>}</section></div>;
}

export function AdminMemberActionDialog({ detail, initial, submitting, error, onClose, onSubmit }: { detail: AdminMemberDetail; initial: AdminMemberActionRequest; submitting: boolean; error: Error | null; onClose: () => void; onSubmit: (request: AdminMemberActionRequest) => void }) {
  const [request, setRequest] = useState(initial); const ref = useRef<HTMLElement>(null); useDialogKeyboard(ref, submitting, onClose);
  const reasons: AdminMemberActionReasonCode[] = request.action === 'UNSUSPEND' ? ['ADMIN_CORRECTION','OTHER'] : ['COMMUNITY_GUIDELINE','HARASSMENT','NO_SHOW_ABUSE','FRAUD_OR_SCAM','SAFETY_RISK','ADMIN_CORRECTION','OTHER'];
  const durations: AdminSuspensionDuration[] = ['ONE_DAY','THREE_DAYS','SEVEN_DAYS','THIRTY_DAYS'];
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-ink/60 p-4"><section ref={ref} role="dialog" aria-modal="true" aria-labelledby="member-action-title" className="w-full max-w-md rounded-3xl bg-white p-6"><h2 id="member-action-title" className="text-lg font-bold">{detail.nickname ?? '회원'} · {actionLabel[request.action]}</h2><p className="mt-2 text-sm text-ink/60">이 조치는 감사 로그에 기록됩니다. Secret, token, OAuth 식별자, GPS 좌표를 입력하지 마세요.</p><label className="mt-4 block text-sm font-semibold">사유<select value={request.reasonCode} onChange={(event) => setRequest({ ...request, reasonCode: event.target.value as AdminMemberActionReasonCode })} className="mt-1 w-full rounded-xl border border-line p-2">{reasons.map((reason) => <option key={reason}>{reason}</option>)}</select></label>{request.action === 'SUSPEND' && <label className="mt-3 block text-sm font-semibold">정지 기간<select value={request.suspensionDuration ?? 'SEVEN_DAYS'} onChange={(event) => setRequest({ ...request, suspensionDuration: event.target.value as AdminSuspensionDuration })} className="mt-1 w-full rounded-xl border border-line p-2">{durations.map((duration) => <option key={duration}>{duration}</option>)}</select></label>}<label className="mt-3 block text-sm font-semibold">메모<textarea maxLength={500} value={request.reasonNote ?? ''} onChange={(event) => setRequest({ ...request, reasonNote: event.target.value || null })} className="mt-1 w-full rounded-xl border border-line p-2"/></label>{error && <p role="alert" aria-live="assertive" className="mt-3 text-sm text-coral">처리하지 못했습니다. 기존 상태는 유지됩니다.</p>}<div className="mt-5 grid grid-cols-2 gap-2"><button disabled={submitting} onClick={onClose} className="rounded-xl border border-line py-3 disabled:opacity-50">취소</button><button disabled={submitting} onClick={() => onSubmit(request)} className="rounded-xl bg-coral py-3 font-bold text-white disabled:opacity-50">{submitting ? '처리 중...' : '확인'}</button></div></section></div>;
}

function useDialogKeyboard(ref: RefObject<HTMLElement>, submitting: boolean, onClose: () => void) {
  useEffect(() => { const dialog = ref.current; if (!dialog) return; const focusables = () => Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),select:not(:disabled),textarea:not(:disabled)')); focusables()[0]?.focus(); const listener = (event: KeyboardEvent) => { if (event.key === 'Escape' && !submitting) { event.preventDefault(); onClose(); } if (event.key === 'Tab') { const values = focusables(); const first = values[0]; const last = values[values.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }; document.addEventListener('keydown', listener); return () => document.removeEventListener('keydown', listener); }, [ref, submitting, onClose]);
}
