spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:meet_or_solo}
    username: ${POSTGRES_USER:meet_or_solo}
    password: ${POSTGRES_PASSWORD:CHANGE_ME_LOCAL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: ${FLYWAY_LOCATIONS:filesystem:../db/migration}
    baseline-on-migrate: false

logging:
  level:
    org.hibernate.SQL: debug
